# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcf6e004408dbba6c170ad168cd8cf743170d9dac0648409bbd0298fb059f4f2630da726fb533085102aac437d457e4b94c775191c0bb8ae319b57e3ef276c34

test:
  secret_key_base: a4d22330b5e46eedcb651d9760f02939184cc1e33dfc8056046131da4771d183640770b65e930722b3fe250f3b59a66726efc47912f4aefdfe9e36fc49352d1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
